#!/usr/bin/env php
<?php

$api_url = "https://v2.jokeapi.dev/joke/Any";
$joke = json_decode(file_get_contents($api_url));


if($joke->type=='single')
{
	echo $joke->joke;
}
else
{
	echo $joke->setup . "\n";
	echo $joke->delivery;
}

?>
